services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: afor-branding
    # ports:
    # - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}

    command: bun run dev
